import { describe, expect, it, vi } from "vitest";
import * as fc from "fast-check";
import {
  applyOp,
  arbEditLipu,
  arbEditLipuPlain,
  arbOps,
  canonicalSegments,
  checkMarkerRelocation,
  checkOracles,
  corpusStats,
  resetCorpusStats,
} from "../../test/edit-corpus";
import { arbBlock } from "../../test/lipu-arbitraries";
import {
  applySeparationDefaults,
  checkBlock,
  JOINER_CHARS,
  mergeLatinBlock,
  mergeSpBlock,
  mergeStructural,
  normalizeLetterishLatin,
  parseLatin,
  parseSp,
  renderLatin,
  renderSp,
  sortSpans,
  tokenizeLatin,
} from "./index";
import type {
  Block,
  Lipu,
  ParsedSide,
} from "./index";
import {
  codepointToChar,
  wordToCodepoint,
  START_OF_CARTOUCHE,
} from "../data";
import {
  CARTOUCHE_END,
  CARTOUCHE_START,
  STACK,
} from "./chars";

import {
  cart,
  latParse as lat,
  rendersBoundToken,
  span,
} from "../../test/helpers";

const latinNoOp = (b: Block): Block =>
  mergeLatinBlock(b, lat(b));
// Bind-shaped blocks (see rendersBoundToken's
// docstring in test/helpers.ts) are exempt from the
// FULL-identity no-op checks below; such blocks are
// not otherwise generated by the two nameless-
// cartouche properties often enough to need their
// own convergence/conservation pair here — the
// bind-transition laws in properties.test.ts cover
// that general claim over the same arbBlock domain.
const spNoOp = (b: Block): Block =>
  mergeSpBlock(b, parseSp(renderSp(b).inlines));
const EMPTY: Block = {
  anchors: [],
  gaps: [{ sp: "", latin: "" }],
  spans: [],
};

const CORPUS = { numRuns: 400 };

describe(
  "edit corpus: oracles 1-5 over " +
    "<=6-op sequences",
  () => {
    const sweep = (
      arb: typeof arbEditLipu
    ): void => {
      resetCorpusStats();
      fc.assert(
        fc.property(arb, arbOps, (lipu, ops) => {
          let cur = lipu;
          for (const op of ops) {
            const { lipu: next, applied } =
              applyOp(cur, op);
            const errs = checkOracles(
              cur,
              next,
              applied
            );
            if (errs.length > 0) {
              throw new Error(
                errs.join("; ") +
                  " on op " +
                  JSON.stringify(op)
              );
            }
            cur = next;
          }
          return true;
        }),
        CORPUS
      );
    };

    it("holds over the shaped corpus", () => {
      sweep(arbEditLipu);
      // The OP side of anti-vacuity. A generator
      // that mints every shape is still vacuous if the
      // alphabet never reaches the paths those shapes
      // live on, so the sweep's own reach is asserted
      // here rather than assumed.
      for (const kind of [
        "insert",
        "delete",
        "replace",
        "enter",
        "split",
        "join",
        "paste",
        "paste-multi",
        "delete-across",
      ]) {
        expect(
          corpusStats.ops[kind] ?? 0
        ).toBeGreaterThan(10);
      }
      expect(
        corpusStats.sideOps.sp ?? 0
      ).toBeGreaterThan(50);
      expect(
        corpusStats.sideOps.latin ?? 0
      ).toBeGreaterThan(50);
      expect(
        corpusStats.structuralOps
      ).toBeGreaterThan(50);
      // ...and the ORACLES' gates: an oracle whose
      // precondition never holds is a comment, not a
      // net.
      //
      // MEASURED FLOOR, not a self-exempting one.
      // Oracle 3's gate is keyed to the system under
      // test — it is the edited side's parse
      // fixpoint — so it can close itself as the
      // merge changes, and `open > closed` has
      // enormous slack at the ~80% this actually
      // runs at. The floor is set just under the
      // measurement so that a change which quietly
      // narrows the gate TRIPS instead of
      // coasting.
      expect(
        corpusStats.oracle3Open /
          (corpusStats.oracle3Open +
            corpusStats.oracle3Closed)
      ).toBeGreaterThan(0.76);
      expect(
        corpusStats.oracle4a + corpusStats.oracle4aPrime
      ).toBeGreaterThan(100);
      expect(
        corpusStats.oracle7Compared
      ).toBeGreaterThan(100);
      // The stranding document-level fallback is
      // rare enough that this sweep may not reach
      // it, so its coverage is a TARGETED test
      // ("the stranding fallback branch is
      // reached") rather than a size-dependent
      // assertion that would make this law flap
      // with numRuns.
      // Oracle 4b's conservation clause ADJUDICATES
      // the large majority of the losses it sees, rather
      // than standing down on all of them.
      expect(
        corpusStats.oracle4bAdjudicated
      ).toBeGreaterThan(
        corpusStats.oracle4bExcused
      );
    });

    it(
      "FAMILY 2 (gap-resident latin disabled) — " +
        "oracles 3 and 4a at full strength",
      () => {
        sweep(arbEditLipuPlain);
        // The gap-resident latin shapes are what make a
        // block latin-parse unstable, and family 1
        // measured a large fraction of oracle-3 and
        // oracle-4 checks landing in the weakened
        // domain because of them. With those two shapes
        // off — and everything else identical — the
        // gates stand open almost everywhere, which is
        // the point of running a second family at
        // all.
        //
        // FLOOR RATIONALE. parseFixpoint (this file,
        // below) is `stable(sideNoOp(b)) ===
        // stable(b)`: is a no-op merge on the edited
        // side an identity? Oracle 3's gate is
        // exactly this predicate, so ANY block still
        // holding an interior-punct multi-anchor run
        // that has not yet transitioned to the bound
        // shape is, BY CONSTRUCTION, not a fixpoint
        // — a Latin no-op legitimately changes it
        // (the same one-time transition priced in
        // properties.test.ts's bind-transition split
        // and the doc-merge.test.ts no-op laws).
        // That is not a narrowing defect; it is the
        // gate correctly reporting that a large
        // fraction of the generated corpus is
        // mid-transition (measured: ~40% of
        // generated documents contain a bound-shaped
        // run before any op runs). The floor sits a
        // few points under the measured open ratio
        // at the committed seed, so a change that
        // quietly narrows the gate trips.
        //
        // (A historical note: at 200 runs this
        // sweep measured 91.2% open; the corpus now
        // runs 400, where the generator-artifact
        // failure that once lurked past run 280 is
        // fixed by the classify wrap in
        // test/edit-corpus.ts.)
        expect(
          corpusStats.oracle3Open /
            (corpusStats.oracle3Open +
              corpusStats.oracle3Closed)
        ).toBeGreaterThan(0.88);
        expect(
          corpusStats.oracle4a +
            corpusStats.oracle4aPrime
        ).toBeGreaterThan(corpusStats.oracle4b);
      }
    );

    it(
      "anti-vacuity: the corpus really reaches " +
        "the minted shapes",
      () => {
        let offsets = 0;
        let emptyName = 0;
        let joiners = 0;
        let letterish = 0;
        let interiorRun = 0;
        let crossPair = 0;
        fc.assert(
          fc.property(arbEditLipu, (lipu) => {
            const docSp = lipu.blocks
              .map((b) =>
                b.gaps.map((g) => g.sp).join("")
              )
              .join("\u0000");
            // a STRAY start in one block and a STRAY
            // end in a LATER one: the pair can never
            // promote, because promotion never
            // crosses a Block boundary
            const cs = docSp.indexOf(CARTOUCHE_START);
            const ce = docSp.lastIndexOf(CARTOUCHE_END);
            if (
              cs >= 0 &&
              ce > cs &&
              docSp
                .slice(cs, ce)
                .includes("\u0000")
            ) {
              crossPair += 1;
            }
            for (const b of lipu.blocks) {
              if (
                b.spans.some(
                  (s) =>
                    (s.kind === "long" ||
                      s.kind === "cartouche") &&
                    s.to > s.from &&
                    b.gaps
                      .slice(s.from + 1, s.to + 1)
                      .some((g) =>
                        g.sp.includes("\n\n")
                      )
                )
              ) {
                interiorRun += 1;
              }
              if (
                b.spans.some(
                  (s) =>
                    s.startOffset !== undefined ||
                    s.endOffset !== undefined
                )
              ) {
                offsets += 1;
              }
              if (
                b.spans.some(
                  (s) =>
                    s.kind === "cartouche" &&
                    b.anchors
                      .slice(s.from, s.to + 1)
                      .every(
                        (a) => a.kind !== "word"
                      )
                )
              ) {
                emptyName += 1;
              }
              if (
                b.gaps.some((g) =>
                  [...g.sp].some((ch) =>
                    JOINER_CHARS.has(ch)
                  )
                )
              ) {
                joiners += 1;
              }
              if (
                b.gaps.some((g) =>
                  /\p{L}|\p{M}/u.test(g.latin)
                )
              ) {
                letterish += 1;
              }
            }
            return true;
          }),
          { numRuns: 300 }
        );
        expect(offsets).toBeGreaterThan(10);
        expect(emptyName).toBeGreaterThan(10);
        expect(joiners).toBeGreaterThan(10);
        expect(letterish).toBeGreaterThan(10);
        expect(interiorRun).toBeGreaterThan(10);
        expect(crossPair).toBeGreaterThan(10);
      }
    );

    it(
      "canonicalSegments is pinned: text splits " +
        "at \\n, empties drop, adjacents merge, " +
        "atoms pass through",
      () => {
        expect(
          canonicalSegments([
            { type: "text", text: "a\n\nb" },
            { type: "text", text: "c" },
          ])
        ).toEqual([
          { kind: "text", text: "a" },
          { kind: "break" },
          { kind: "break" },
          { kind: "text", text: "bc" },
        ]);
      }
    );
  }
);

describe(
  "the equal-count reshape's relocation, pinned",
  () => {
    it(
      "positional pairing loses prev-side content " +
        "on re-created anchors and can strand an " +
        "interior \\n\\n gap.latin — EXACT pin",
      () => {
        const W = (w: string) => ({
          kind: "word" as const,
          word: w,
        });
        const prev: Block[] = [
          {
            anchors: [W("toki")],
            gaps: [
              { sp: "", latin: "" },
              { sp: "", latin: "\n\n" },
            ],
            spans: [],
          },
          {
            anchors: [W("pona")],
            gaps: [
              { sp: "", latin: ". " },
              { sp: "", latin: "" },
            ],
            spans: [],
          },
        ];
        // reshape: same count, different boundary —
        // paragraph 0 now holds both words, 1 empty
        const sides: ParsedSide[] = [
          {
            anchors: [W("toki"), W("pona")],
            gaps: ["", " ", ""],
          },
          { anchors: [], gaps: [""] },
        ];
        const out = mergeStructural(
          prev,
          sides,
          "sp"
        );
        // FROZEN (run-derived). Losses this value
        // exhibits, all from POSITIONAL pairing:
        //  1. STRANDED "\n\n": it was paragraph 0's
        //     TRAILING gap.latin — the Latin text of
        //     the paragraph BOUNDARY — and positional
        //     pairing leaves it on toki's owned gap,
        //     so it is now an INTERIOR "\n\n" between
        //     toki and pona inside one paragraph.
        //  2. LOST ". ": prev paragraph 1's leading
        //     gap.latin stays with the now-EMPTY
        //     paragraph 1 instead of following "pona"
        //     into paragraph 0.
        //  3. The "pona" anchor in paragraph 0 is
        //     RE-CREATED (prev paragraph 0 never had
        //     it), so it takes the creation default
        //     rather than carrying prev "pona"'s
        //     gap.latin.
        // The registry accepts exactly this class
        // (the edge-split relocation). The pin
        // exists so any change to it is loud.
        expect(out).toEqual([
          {
            anchors: [W("toki"), W("pona")],
            gaps: [
              { sp: "", latin: "" },
              { sp: " ", latin: "\n\n" },
              { sp: "", latin: "" },
            ],
            spans: [],
          },
          {
            anchors: [],
            gaps: [{ sp: "", latin: ". " }],
            spans: [],
          },
        ]);
      }
    );
  }
);

describe(
  "migrated block-leading latin on " +
    "Enter-Enter",
  () => {
    it(
      "pins where block-leading gap.latin lands " +
        "when the block splits at position 0",
      () => {
        const prev: Lipu = {
          version: 2,
          blocks: [
            {
              anchors: [
                { kind: "word", word: "toki" },
              ],
              gaps: [
                { sp: "", latin: "ni " },
                { sp: "", latin: "" },
              ],
              spans: [],
            },
          ],
        };
        const { lipu: out } = applyOp(prev, {
          kind: "split",
          side: "sp",
          block: 0,
          pos: 0,
          len: 0,
          text: "",
        });
        // FROZEN (run-derived). The migrated
        // block-leading "ni " LANDS ON THE EMPTY
        // PARAGRAPH. gaps[0] is Block-owned, the
        // split puts the block-owned gap with the
        // LEFT chunk, and routeSplitGaps' latin
        // division finds no "\n" run to divide at
        // (splitLatin("ni ") is all left), so
        // nothing routes right.
        //
        // NOT FIXED, deliberately: a local fix in
        // routeSplitGaps' latin routing does not
        // exist — routing "ni " right would have to
        // override the trailing-run division for the
        // whole zero-newline case, which is the same
        // code path that correctly leaves a
        // line-join's companion "\n" alone. Pinned
        // and reported instead.
        expect(out.blocks).toEqual([
          {
            anchors: [],
            gaps: [{ sp: "", latin: "ni " }],
            spans: [],
          },
          {
            anchors: [{ kind: "word", word: "toki" }],
            gaps: [
              { sp: "", latin: "" },
              { sp: "", latin: "" },
            ],
            spans: [],
          },
        ]);
      }
    );
  }
);

describe(
  "accepted: rechunk drops a formatting span " +
    "straddling a zero-anchor chunk",
  () => {
    it(
      "a split minting an empty paragraph inside " +
        "a bold span drops the span for that chunk",
      () => {
        const prev: Lipu = {
          version: 2,
          blocks: [
            {
              anchors: [
                { kind: "word", word: "toki" },
                { kind: "word", word: "pona" },
              ],
              gaps: [
                { sp: "", latin: "" },
                { sp: " ", latin: " " },
                { sp: "", latin: "" },
              ],
              spans: [
                span("bold", 0, 1),
              ],
            },
          ],
        };
        // sp split between the words TWICE at the
        // same point -> middle paragraph is empty
        const { lipu: once } = applyOp(prev, {
          kind: "split",
          side: "sp",
          block: 0,
          pos: 3,
          len: 0,
          text: "",
        });
        const { lipu: out } = applyOp(once, {
          kind: "split",
          side: "sp",
          block: 1,
          pos: 0,
          len: 0,
          text: "",
        });
        expect(out.blocks).toHaveLength(3);
        // the zero-anchor middle block carries NO
        // span (dropped by rechunk, accepted); the
        // outer chunks keep theirs
        const middle = out.blocks.find(
          (b) => b.anchors.length === 0
        );
        expect(middle).toBeDefined();
        expect(middle!.spans).toEqual([]);
        for (const b of out.blocks) {
          expect(checkBlock(b)).toEqual([]);
        }
      }
    );
  }
);

// ---------------------------------------------------
// CORPUS FINDINGS — disposition.
//
// Every describe below pins a behaviour this corpus
// FOUND. Nothing here is still open: each finding is
// either FIXED (its pin is a regression lock on the
// fix) or REGISTERED as an accepted limitation (its
// pin is the exact-expectation pin the registry
// requires).
//
//   FIXED
//     - the fusion-guard fixpoint gaps: the
//       letterish pass composed into the SP merge
//       chains; its exemption re-keyed to atomized
//       anchors; the LETTERISH_START widening.
//     - the degenerate-adjacency mint:
//       mergeLatinBlock's one SP-side separation
//       default, scoped to ADJACENCY-level
//       freshness.
//     - the split-rebase coordinate mix: the rebase
//       refuses a gap the merge rewrote.
//     - the ATOMIZATION RULE: a nameless cartouche
//       no longer atomizes.
//     - the SPAN KIND-CHANGE RULE: a structural
//       span does not follow a replacement pairing
//       onto an anchor of a different KIND; it dies.
//     - the duplicate-word alignment bug: LCS
//       occurrence-aware secondary keying on
//       flanking-gap content, latin-only, adopted
//       under a set-inclusion conservation gate.
//
//   REGISTERED (accepted limitations)
//     - the edge-split relocation of a following
//       paragraph's leading gap.
//     - the flat-path stranding (until
//       transaction-level mapping exists).
//     - identical-word victim selection (pinned in
//       merge.test.ts, not here).
//     - the whitespace-verbatim split-half
//       misalignment (pinned below; it is the
//       seed-1 limit the SEED SCOPE header
//       records).
//
//   WITHDRAWN — one reported fusion-guard door was
//   not reproduced as characterized; the withdrawal
//   note is in test/edit-corpus.ts's diagnoseSpLoss
//   doc comment.
// ---------------------------------------------------

// FIXED: mergeSpBlock and mergeStructural's sp arm
// compose normalizeLetterishLatin AFTER the
// separation default, so an SP edit that newly abuts
// stored letter-ish gap.latin -- or uncovers a
// cartouche flank that was exempt at load time --
// re-establishes the fusion-guard fixpoint instead
// of leaving it for the next Latin no-op to destroy.
// See doc-merge.ts's shared sp pass chain for the
// exact composition point.
describe(
  "the SP merge chain re-establishes the latin " +
    "fusion-guard fixpoint",
  () => {
    it(
      "(a) an SP insert next to gap-resident latin " +
        "letters is separated by the composed " +
        "letterish pass, and the next Latin no-op " +
        "round-trips " +
        "with the word anchor's glyph intact",
      () => {
        // AT the letterish fixpoint: no anchors,
        // nothing to fuse with, so
        // normalizeLetterishLatin is identity here.
        const b0: Block = {
          anchors: [],
          gaps: [{ sp: "", latin: "ax" }],
          spans: [],
        };
        // the user types the toki glyph in the SP pane
        const b1 = mergeSpBlock(
          b0,
          parseSp([
            {
              type: "text",
              text: "\u{F196C}",
              verbatim: false,
            },
          ])
        );
        // FIXED: "ax" ends in a letter, adjacent to
        // "toki"'s letter start -- mergeSpBlock's
        // composed normalizeLetterishLatin pass
        // separates it (trailing " "), where the
        // separation default alone (fires only on
        // latin === "") would not.
        expect(b1).toEqual({
          anchors: [{ kind: "word", word: "toki" }],
          gaps: [
            { sp: "", latin: "ax " },
            { sp: "", latin: "" },
          ],
          spans: [],
        });
        expect(renderSp(b1).text).toBe("\u{F196C}");
        // ...and the Latin no-op no longer eats the
        // glyph: "ax" promotes to its OWN verbatim
        // anchor (the pinned anchor-material
        // behavior), and "toki" SURVIVES as a word
        // anchor.
        const rt = latinNoOp(b1);
        expect(rt).toEqual({
          anchors: [
            {
              kind: "verbatim",
              text: "ax",
              marked: true,
            },
            { kind: "word", word: "toki" },
          ],
          gaps: [
            { sp: "", latin: "" },
            { sp: "", latin: " " },
            { sp: "", latin: "" },
          ],
          spans: [],
        });
        // idempotent: a second Latin no-op is a
        // true fixed point (same discipline as the
        // letterish pins)
        expect(latinNoOp(rt)).toEqual(rt);
      }
    );

    it(
      "(c) an SP edit that dissolves a cartouche " +
        "uncovers previously-exempt mark-leading " +
        "gap.latin, and the composed pass catches it " +
        "on that SAME merge -- the covered() " +
        "exemption at the boundary was correct AT " +
        "LOAD TIME, but is not permanent",
      () => {
        const b0: Block = {
          anchors: [{ kind: "word", word: "toki" }],
          gaps: [
            { sp: "", latin: "" },
            { sp: "", latin: "\u0301ax" },
          ],
          spans: [
            cart(0, 0),
          ],
        };
        // covered() correctly exempts the boundary
        // while the cartouche stands
        expect(normalizeLetterishLatin(b0)).toBe(b0);
        // the user deletes the cartouche's END char in
        // the SP pane (START char, then the glyph, then
        // nothing -- END is gone)
        const edited = parseSp([
          {
            type: "text",
            text:
              codepointToChar(START_OF_CARTOUCHE) +
              codepointToChar(wordToCodepoint["toki"]),
            verbatim: false,
          },
        ]);
        const out = mergeSpBlock(b0, edited);
        // the span DIED (no matching END marker) --
        // the stray START char is ordinary gap
        // content now, not a structural marker
        expect(out.spans).toEqual([]);
        // FIXED: anchor 0 is no longer covered, and the
        // composed pass sees it and the mark-leading
        // gap.latin on THIS SAME merge -- a leading " "
        // is inserted
        expect(out.gaps[1].latin).toBe(" \u0301ax");
        // ...so the following Latin no-op keeps the
        // "toki" WORD anchor -- pre-fix this collapsed
        // to one marked verbatim "toki" + U+0301 +
        // "ax" (glyph destroyed; verified live)
        const rt = latinNoOp(out);
        expect(
          rt.anchors.some((a) => a.kind === "word")
        ).toBe(true);
        expect(rt.anchors[0]).toEqual({
          kind: "word",
          word: "toki",
        });
      }
    );

    it(
      "(d) a mark-LEADING anchor (its own rendered " +
        "latin starts with a combining mark, not a " +
        "letter -- a LETTER_START next-anchor " +
        "gate would miss it) still gets the RIGHT " +
        "boundary separated, because tokenizeLatin's " +
        "run continues into a mark exactly as it " +
        "continues into a letter",
      () => {
        const b: Block = {
          anchors: [
            { kind: "word", word: "toki" },
            {
              kind: "verbatim",
              text: "\u0301bc",
              marked: true,
            },
          ],
          gaps: [
            { sp: "", latin: "" },
            { sp: "", latin: "ax" },
            { sp: "", latin: "" },
          ],
          spans: [],
        };
        const n = normalizeLetterishLatin(b);
        // both boundaries separated: left because
        // "toki" ends in a letter and "ax" starts with
        // one (ordinary case); right because "ax" ends
        // in a letter and the mark-leading anchor
        // continues an active run just as a
        // letter-leading one would -- reachability
        // from editor gestures is unproven; this
        // pins the merge-level contract
        // fusesRight/fusesLeft already support.
        expect(n.gaps[1].latin).toBe(" ax ");
        expect(normalizeLetterishLatin(n)).toBe(n);
      }
    );
  }
);

// FIXED: mergeLatinBlock applies
// exactly ONE SP-side separation default (the SP
// analogue): a fresh SP-degenerate ADJACENCY
// between two MARKED VERBATIM anchors across an empty
// gap.sp gets a single " ", since renderSp coalesces two
// adjacent marked-verbatim runs into ONE inline text
// node purely on the `verbatim` flag matching
// (render-sp.ts's pushText), independent of content. See
// doc-merge.ts's applyMarkedVerbatimSpDefault. Skipped
// only when the pair was ALREADY adjacent in prev (an
// already-settled pair must stay untouched, or a bare
// Latin no-op on an unrelated block would start
// inventing SP bytes on a backbone-stable reparse -- the
// edit-corpus law's oracle4a, caught live on a
// cartouche-covered anchor freshly split next to a
// promoted "ax").
//
// ANCHOR-level freshness (prevIndexOf undefined on a
// flank) is necessary but not sufficient -- see
// "adjacency-level reopen" below for the
// adversarial case that scoping misses, and
// applyMarkedVerbatimSpDefault's comment for the
// ADJACENCY-level test.
describe(
  "mergeLatinBlock's composed SP default " +
    "protects a freshly minted adjacency",
  () => {
    it(
      "two adjacent MARKED verbatims no longer fuse " +
        "on reparse -- the promoted anchor's gap.sp " +
        "gets a separating space instead of the " +
        "empty creation default",
      () => {
        const b: Block = {
          anchors: [
            {
              kind: "verbatim",
              text: "xq",
              marked: true,
            },
          ],
          gaps: [
            { sp: "", latin: "" },
            { sp: "", latin: " ax" },
          ],
          spans: [],
        };
        // a Latin edit promotes "ax" -- the core
        // still stands (no Latin analogue of the
        // Enter default, no separation default on a
        // parse-authoritative Latin edit), but the
        // one authorized SP default fires because
        // "ax" is a FRESH mint next to a marked
        // verbatim
        const one = latinNoOp(b);
        expect(one.anchors).toEqual([
          { kind: "verbatim", text: "xq", marked: true },
          { kind: "verbatim", text: "ax", marked: true },
        ]);
        // FIXED: was "" pre-fix; the composed default
        // separates the pair on THIS SAME merge
        expect(one.gaps[1].sp).toBe(" ");
        // ...so both anchors now render as DISTINCT
        // inline runs (the gap's " " renders
        // non-verbatim, breaking pushText's coalescing),
        // and the follow-up SP no-op is a TRUE no-op --
        // pre-fix this collapsed to one verbatim
        // "xqax", losing the anchor boundary
        const two = spNoOp(one);
        expect(two).toEqual(one);
      }
    );

    it(
      "adjacency-level reopen: two ALREADY " +
        "CARRIED marked verbatims, flanking a WORD " +
        "anchor that a Latin edit deletes, become " +
        "newly adjacent -- an anchor-level mint check " +
        "misses this (neither flank is individually " +
        "new)",
      () => {
        const prev: Block = {
          anchors: [
            {
              kind: "verbatim",
              text: "xq",
              marked: true,
            },
            { kind: "word", word: "toki" },
            {
              kind: "verbatim",
              text: "ax",
              marked: true,
            },
          ],
          gaps: [
            { sp: "", latin: "" },
            { sp: "", latin: " " },
            { sp: "", latin: " " },
            { sp: "", latin: "" },
          ],
          spans: [],
        };
        expect(renderLatin(prev).text).toBe(
          "xq toki ax"
        );
        // Latin delete of "toki" ONLY, keeping both
        // flanking spaces: "xq" + " " + "" + " " + "ax"
        const parsed = parseLatin([
          { type: "text", text: "xq  ax" },
        ]);
        const out = mergeLatinBlock(prev, parsed);
        // "xq" and "ax" are each individually CARRIED
        // (prevIndexOf defined for both, at prev
        // indices 0 and 2) -- but were NOT adjacent in
        // prev (index 2 !== index 0 + 1), so the
        // adjacency-level check fires anyway
        expect(out.anchors).toEqual([
          { kind: "verbatim", text: "xq", marked: true },
          { kind: "verbatim", text: "ax", marked: true },
        ]);
        expect(out.gaps[1]).toEqual({
          sp: " ",
          latin: "  ",
        });
        // the follow-up SP round-trip keeps BOTH
        // anchors -- an anchor-level-only check
        // fused this into one verbatim "xqax" (the
        // exact bug, reopened via ordinary word
        // deletion)
        const two = spNoOp(out);
        expect(two).toEqual(out);
      }
    );
  }
);

describe(
  "edge-split relocation: a split at a paragraph " +
    "EDGE relocates the " +
    "following paragraph's leading gap",
  () => {
    it(
      "the carried side of paragraph 1's gaps[0] " +
        "moves to the newly minted empty paragraph",
      () => {
        const P0: Block = {
          anchors: [{ kind: "word", word: "toki" }],
          gaps: [
            { sp: "", latin: "" },
            { sp: "", latin: "" },
          ],
          spans: [],
        };
        const P1: Block = {
          anchors: [{ kind: "word", word: "pona" }],
          gaps: [
            { sp: "  ", latin: ", " },
            { sp: "", latin: "" },
          ],
          spans: [],
        };
        // a LATIN split at the end of P0: 2 -> 3
        const out = mergeStructural(
          [P0, P1],
          [lat(P0), lat(EMPTY), lat(P1)],
          "latin"
        );
        // P1's carried gap.sp "  " is now the EMPTY
        // paragraph's; P1 keeps only its edited
        // (parse-authoritative) side. Content is
        // RELOCATED, never destroyed ("gap CONTENT
        // is never lost" still holds document-wide)
        // — but it changed paragraph.
        expect(out).toEqual([
          P0,
          {
            anchors: [],
            gaps: [{ sp: "  ", latin: "" }],
            spans: [],
          },
          {
            anchors: [{ kind: "word", word: "pona" }],
            gaps: [
              {
                sp: "",
                latin: ", ",
                latinAuthored: true,
              },
              { sp: "", latin: "" },
            ],
            spans: [],
          },
        ]);
      }
    );
  }
);

describe(
  "flat-path stranding: a count-changing LATIN " +
    "merge strands a " +
    "parse-unstable anchor across paragraphs",
  () => {
    it(
      "the stranded paragraph's SP bytes are " +
        "DESTROYED",
      () => {
        // P1's anchor renders as pure punctuation on
        // the Latin side, so its own parse returns it
        // to gap.latin; only merge.ts's re-absorption
        // normally rescues it.
        const P1: Block = {
          anchors: [
            {
              kind: "verbatim",
              text: "-",
              marked: true,
            },
          ],
          gaps: [
            { sp: "", latin: "" },
            { sp: "X", latin: "" },
          ],
          spans: [],
        };
        // P2 holds a SAME-RENDERING anchor plus
        // gap-resident anchor material that promotes
        // on any Latin parse, which is what shifts the
        // flat stream's alignment.
        const P2: Block = {
          anchors: [
            {
              kind: "verbatim",
              text: "-",
              marked: true,
            },
          ],
          gaps: [
            { sp: "", latin: "ni ax" },
            { sp: "", latin: "" },
          ],
          spans: [
            cart(0, 0),
          ],
        };
        const prev = [EMPTY, P1, P2];
        expect(
          prev.map((b) => renderSp(b).text)
        ).toEqual([
          "",
          "-X",
          "\u{F1990}-\u{F1991}",
        ]);
        // a LATIN split of the empty first paragraph
        const out = mergeStructural(
          prev,
          [lat(EMPTY), lat(EMPTY), lat(P1), lat(P2)],
          "latin"
        );
        // P1's anchor is stranded: it AND its gap.sp
        // "X" are gone from the document.
        // mergeStructural's fast-path note names this
        // hazard and answers it for EQUAL counts only;
        // a split has no fast path.
        //
        // P2's cartouche is nameless, so it does
        // not atomize and its "-" re-tokenizes into
        // gap.latin like P1's. The flat LCS then
        // finds NO common anchor at all (prev
        // "-","-" vs next "ni","ax"), so
        // re-absorption places one "-" and
        // positional replacement pairing hands the
        // cartouche to the OTHER paragraph. The LOSS
        // is one stranded anchor, its SP byte "X"
        // destroyed — inside the registered
        // stranding acceptance (count-changing Latin
        // merge, competing same-rendering anchor,
        // migrated-content trigger).
        expect(
          out.map((b) => renderSp(b).text)
        ).toEqual([
          "",
          "",
          "\u{F1990}-\u{F1991}",
          "\u{F1941}ax",
        ]);
      }
    );
  }
);

describe(
  "the flat-path startOffset rebase refuses a " +
    "gap the merge rewrote (coordinate mix FIXED)",
  () => {
    it(
      "crossAt is measured on the MERGED gap, so a " +
        "PREV-gap offset is dropped, not rebased",
      () => {
        const b: Block = {
          anchors: [
            {
              kind: "verbatim",
              text: "aa",
              marked: true,
            },
          ],
          gaps: [
            // STACK (a joiner) + "\n"; the offset 2
            // sits between them, on a boundary, and is
            // valid for THIS string
            { sp: "\u{F1995}\n", latin: "́" },
            { sp: "", latin: "" },
          ],
          spans: [
            cart(0, 0, { startOffset: 2 }),
          ],
        };
        const seen: string[] = [];
        const spy = vi
          .spyOn(console, "error")
          .mockImplementation((...a: unknown[]) => {
            seen.push(String(a[0]));
          });
        let out: Block[];
        try {
          // a LATIN split at position 0
          out = mergeStructural(
            [b],
            [lat(EMPTY), lat(b)],
            "latin"
          );
        } finally {
          spy.mockRestore();
        }
        // cleanupJoiners removes the unflanked
        // joiner from the DISTURBED gap inside
        // mergeBlockDetailed, so the merged gap.sp is
        // "\n" while prev's was STACK + "\n".
        // routeSplitGaps measures crossAt against the
        // MERGED string, while ps.startOffset indexes
        // the PREV one — two different coordinate
        // systems, so the subtraction is meaningless.
        //
        // FIXED (this generator's finding): the
        // rebase requires the prev gap to be
        // BYTE-IDENTICAL to the divided string, so
        // this offset is dropped where it is
        // unrepresentable (the registered drop rule)
        // instead of being rebased into nonsense.
        // Same output
        // block as before — the difference is that the
        // drop is now BY RULE, so the tripwire stays
        // silent. (The pin's earlier value was that
        // the tripwire caught the out-of-range half of
        // the bug; the in-range half was silent, and
        // that is the half this fix removes — see
        // doc-merge.test.ts "COORDINATE MIX PIN".)
        expect(seen).toEqual([]);
        // the marker snaps to its anchor-adjacent
        // default; no gap CONTENT is lost.
        expect(out!).toEqual([
          EMPTY,
          {
            anchors: [
              {
                kind: "verbatim",
                text: "aa",
                marked: true,
              },
            ],
            gaps: [
              {
                sp: "",
                latin: "́",
                latinAuthored: true,
              },
              { sp: "", latin: "" },
            ],
            spans: [
              cart(0, 0),
            ],
          },
        ]);
      }
    );
  }
);

describe(
  "an EMPTY-NAME cartouche no longer atomizes, " +
    "so the Latin projection can see it (FIXED)",
  () => {
    it(
      "a Latin no-op carries the span and its SP " +
        "marker chars (migrated repro re-derived)",
      () => {
        const b: Block = {
          anchors: [
            {
              kind: "verbatim",
              text: "-",
              marked: true,
            },
            {
              kind: "verbatim",
              text: "-",
              marked: true,
            },
          ],
          gaps: [
            { sp: "\n", latin: "ni " },
            { sp: "\u{F1995}\u{F1990} ", latin: "" },
            { sp: "", latin: "" },
          ],
          spans: [
            cart(1, 1),
          ],
        };
        // The cartouche covers a MARKED VERBATIM,
        // so its Latin name text is "". BEFORE the
        // atomization-rule fix renderLatin emitted a
        // ZERO-WIDTH atom there: an ANCHOR in the
        // parse at a position
        // where the projection emitted no CHARACTERS,
        // which the merge's rendered-text alignment
        // pairs with the FIRST same-rendering anchor
        // in the block ("-" at index 0). The real one
        // was then stranded in a region its own text
        // never reaches, and step 2 deleted it — atom,
        // cartouche span and SP marker chars all gone,
        // settling only after THREE no-ops:
        //   "\n[NI]-[STACK][ "   (span: none)
        // NOW:
        // a nameless cartouche does not atomize, so
        // its content projects as ordinary Latin text,
        // anchors and characters stay in
        // correspondence, and nothing is lost. The
        // only change across the trace is step 1's
        // promotion of the migrated block-leading
        // "ni " — after that it is a fixpoint.
        const sp = [renderSp(b).text];
        let cur = b;
        for (let i = 0; i < 3; i++) {
          cur = latinNoOp(cur);
          sp.push(renderSp(cur).text);
        }
        expect(sp).toEqual([
          "\n-\u{F1995}\u{F1990} \u{F1990}-\u{F1991}",
          "\n\u{F1941}-\u{F1995}\u{F1990} " +
            "\u{F1990}-\u{F1991}",
          "\n\u{F1941}-\u{F1995}\u{F1990} " +
            "\u{F1990}-\u{F1991}",
          "\n\u{F1941}-\u{F1995}\u{F1990} " +
            "\u{F1990}-\u{F1991}",
        ]);
        // the span survives, over the "ni"-shifted
        // anchor index
        expect(cur.spans).toEqual([
          cart(2, 2),
        ]);
        expect(renderLatin(cur).text).toBe("ni --");
      }
    );

    it(
      "NATIVE (no migrated content): the SP text " +
        "typed by hand is a Latin no-op FIXPOINT",
      () => {
        // Pure SP typing, no migrated gap.latin
        // anywhere.
        const spText =
          "-" +
          STACK +
          CARTOUCHE_START +
          " " +
          CARTOUCHE_START +
          "-" +
          CARTOUCHE_END;
        const b = mergeSpBlock(
          EMPTY,
          parseSp([
            {
              type: "text",
              text: spText,
              verbatim: false,
            },
          ])
        );
        expect(checkBlock(b)).toEqual([]);
        expect(renderSp(b).text).toBe(
          "-\u{F1995}\u{F1990} \u{F1990}-\u{F1991}"
        );
        // the nameless cartouche's content is now
        // VISIBLE in the projection (it was "- ")
        expect(renderLatin(b).text).toBe("- -");
        // BEFORE the atomization-rule fix the
        // first Latin no-op
        // turned the SP text into "-\u{F1995}\u{F1990} "
        // — atom, span and both marker chars gone, the
        // covered "-" surviving only as gap.latin " -".
        const one = latinNoOp(b);
        expect(one).toEqual(b);
        expect(latinNoOp(one)).toEqual(b);
      }
    );

    // The two pins above are instances; this is
    // the class. Both properties FAIL on pre-fix
    // code (verified by revert) with the span, an
    // anchor
    // and its gap destroyed — they are the reason to
    // believe the fix closed the shape rather than
    // the two fixtures.
    it(
      "generator-backed: a nameless cartouche over " +
        "ANY verbatim anchor is Latin-no-op stable",
      () => {
        fc.assert(
          fc.property(
            arbBlock,
            fc.nat(20),
            (b0, k) => {
              const idx = b0.anchors
                .map((a, i) => [a, i] as const)
                .filter(
                  ([a]) => a.kind === "verbatim"
                )
                .map(([, i]) => i);
              if (idx.length === 0) return;
              const at = idx[k % idx.length];
              const b = applySeparationDefaults({
                ...b0,
                spans: sortSpans([
                  ...b0.spans,
                  cart(at, at),
                ]),
              });
              if (checkBlock(b).length > 0) return;
              // bind-shaped blocks transition
              // rather than no-op.
              if (rendersBoundToken(b)) return;
              expect(latinNoOp(b)).toEqual(b);
            }
          ),
          CORPUS
        );
      }
    );

    it(
      "generator-backed: an explicitly EMPTY " +
        "latinSpelling is stable over any anchor",
      () => {
        fc.assert(
          fc.property(
            arbBlock,
            fc.nat(20),
            (b0, k) => {
              if (b0.anchors.length === 0) return;
              const at = k % b0.anchors.length;
              const b = applySeparationDefaults({
                ...b0,
                spans: sortSpans([
                  ...b0.spans,
                  cart(at, at, { attrs: { latinSpelling: "" } }),
                ]),
              });
              if (checkBlock(b).length > 0) return;
              // bind-shaped blocks transition
              // rather than no-op.
              if (rendersBoundToken(b)) return;
              expect(latinNoOp(b)).toEqual(b);
            }
          ),
          CORPUS
        );
      }
    );
  }
);

describe(
  "the stranding fallback branch is " +
    "reached",
  () => {
    it(
      "the stranding shape drives oracle 2 into " +
        "its document-level clause",
      () => {
        // Same shape as the stranding pin above:
        // P1's
        // anchor renders as pure punctuation on the
        // Latin side (its raw parse drops it), P2 holds
        // a same-rendering anchor plus gap-resident
        // anchor material. A latin split of the empty
        // first paragraph strands P1 — a per-block
        // oracle-2 failure — and the document-level
        // clause is what adjudicates it.
        const P1: Block = {
          anchors: [
            {
              kind: "verbatim",
              text: "-",
              marked: true,
            },
          ],
          gaps: [
            { sp: "", latin: "" },
            { sp: "X", latin: "" },
          ],
          spans: [],
        };
        const P2: Block = {
          anchors: [
            {
              kind: "verbatim",
              text: "-",
              marked: true,
            },
          ],
          gaps: [
            { sp: "", latin: "ni ax" },
            { sp: "", latin: "" },
          ],
          spans: [
            cart(0, 0),
          ],
        };
        const prev: Lipu = {
          version: 2,
          blocks: [EMPTY, P1, P2],
        };
        resetCorpusStats();
        const { lipu: next, applied } = applyOp(
          prev,
          {
            kind: "split",
            side: "latin",
            block: 0,
            pos: 0,
            len: 0,
            text: "",
          }
        );
        const errs = checkOracles(
          prev,
          next,
          applied
        );
        // the branch RAN...
        expect(
          corpusStats.strandingFallbackTaken
        ).toBe(1);
        // ...and adjudicated: the registered
        // acceptance covers the SP-byte loss, and
        // the clause's own statement (the parse's
        // edited-side text survives) holds.
        expect(errs).toEqual([]);
      }
    );
  }
);

describe(
  "oracle 7 catches an IN-RANGE marker " +
    "relocation the tripwire cannot see",
  () => {
    // The net for the coordinate-mix class, verified
    // against the PRE-FIX code (routeSplitGaps with
    // the `prev.gaps[leftPrev].sp === orig` clause
    // removed) rather than merely designed for it.
    //
    // Fixture: gaps[1].sp is a leading JOINER plus
    // "xy\nzwvu", with the cartouche's startOffset at 6
    // (right after the "z"). A LATIN split divides that
    // gap; cleanupJoiners has already removed the
    // unflanked joiner from the merged copy, so crossAt
    // is measured on a string two units shorter than
    // the one the offset indexes. Pre-fix the rebase
    // yields startOffset 3 into "zwvu" — IN RANGE, on a
    // codepoint boundary, so revalidateSpanOffsets
    // keeps it and the tripwire stays SILENT — while
    // the marker's correct place is offset 1. Verified
    // live: pre-fix tripwire=false, oracle7 FIRES;
    // post-fix the rebase is refused, the offset is
    // absent, oracle7 is silent.
    const covered: Block = {
      anchors: [{ kind: "word", word: "pona" }],
      gaps: [
        // spAuthored: true (the OR rule) --
        // gaps[1].sp on `before` restamps AUTHORED
        // by the recognizer once cleanupJoiners
        // strips its leading STACK joiner (a carried-
        // side byte change); routeSplitGaps then ORs
        // that mark into this receiving half when the
        // LATIN split divides the carried sp run.
        { sp: "zwvu", latin: " ", spAuthored: true },
        { sp: "pq", latin: "" },
      ],
      spans: [
        cart(0, 0),
      ],
    };
    const before: Lipu = {
      version: 2,
      blocks: [
        {
          anchors: [
            { kind: "word", word: "toki" },
            { kind: "word", word: "pona" },
          ],
          gaps: [
            { sp: "", latin: "" },
            { sp: STACK + "xy\nzwvu", latin: " " },
            { sp: "pq", latin: "" },
          ],
          spans: [
            cart(1, 1, { startOffset: 6 }),
          ],
        },
      ],
    };
    const halves = (span: Block["spans"]): Lipu => ({
      version: 2,
      blocks: [
        {
          anchors: [{ kind: "word", word: "toki" }],
          gaps: [
            { sp: "", latin: "" },
            {
              sp: "xy",
              latin: "",
              spAuthored: true,
            },
          ],
          spans: [],
        },
        { ...covered, spans: span },
      ],
    });

    it("is SILENT on the fixed output", () => {
      const { lipu: after } = applyOp(before, {
        kind: "split",
        side: "latin",
        block: 0,
        pos: 4,
        len: 0,
        text: "",
      });
      // the fix refuses the rebase: absent offset,
      // which is the registered anchor-adjacent
      // default
      expect(after.blocks).toEqual(
        halves([
          cart(0, 0),
        ]).blocks
      );
      expect(
        checkMarkerRelocation(
          before,
          after,
          true,
          "latin"
        )
      ).toEqual([]);
    });

    it("FIRES on the pre-fix output", () => {
      // the exact block the pre-fix rebase produced
      const preFix = halves([
        cart(0, 0, { startOffset: 3 }),
      ]);
      // checkBlock is happy with it — that is the whole
      // problem, and why the tripwire never sees it
      for (const b of preFix.blocks) {
        expect(checkBlock(b)).toEqual([]);
      }
      expect(
        checkMarkerRelocation(
          before,
          preFix,
          true,
          "latin"
        )
      ).toEqual([
        "oracle7 START marker RELOCATED inside its " +
          'gap (cartouche|[{"kind":"word","word":' +
          '"pona"}])',
      ]);
    });
  }
);

// FIXED, by the SPAN KIND-CHANGE RULE (found by
// the multi-paragraph paste op, the gesture nothing
// else could express): a structural span does not
// follow a REPLACEMENT PAIRING onto an anchor of a
// different KIND -- it dies instead, under the
// span-death licence. The prev cartouche covered a
// marked VERBATIM "-"; the paste put a WORD there,
// so the span does not follow and the pane keeps
// showing what the user pasted. Editor-layer
// post-pass (doc-merge's dropKindChangedSpans,
// pinned both directions in doc-merge.test.ts "SPAN
// KIND-CHANGE RULE").
describe(
  "a carried cartouche does NOT re-atomize " +
    "freshly pasted Latin text (kind-change rule)",
  () => {
    it(
      "the pasted \"mi\" stays visible: the span " +
        "DIES rather than following the replacement " +
        "pairing onto a different anchor KIND",
      () => {
        const withCartouche = (
          sp: string
        ): Block => ({
          anchors: [
            {
              kind: "verbatim",
              text: "-",
              marked: true,
            },
          ],
          gaps: [
            { sp, latin: "ni ́ax" },
            { sp: "", latin: "" },
          ],
          spans: [
            cart(0, 0),
          ],
        });
        const prev: Lipu = {
          version: 2,
          blocks: [
            withCartouche(STACK),
            withCartouche(""),
            withCartouche(""),
          ],
        };
        // a multi-paragraph paste over the selection
        // spanning paragraphs 0 and 1
        const { lipu: out, applied } = applyOp(prev, {
          kind: "paste-multi",
          side: "latin",
          block: 0,
          pos: 0,
          len: 1,
          text: "mi\n\nli",
        });
        // the parse asserted the pasted "mi"...
        expect(applied.editedUnits).toContain("mi");
        // ...and paragraph 0 still SHOWS it. Pre-rule
        // the carried cartouche came back over the
        // fresh word anchor and the pane rendered the
        // span's projected name atom "M" instead of
        // the pasted characters. Under the
        // kind-change rule the span dies (prev covered
        // a marked VERBATIM, the paste put a WORD
        // there) -- span death by text edit is
        // permitted, and no span was ever CREATED on
        // the Latin side.
        expect(out.blocks[0]).toEqual({
          anchors: [{ kind: "word", word: "mi" }],
          gaps: [
            { sp: STACK, latin: "" },
            { sp: "", latin: "" },
          ],
          spans: [],
        });
        expect(renderLatin(out.blocks[0]).text).toBe(
          "mi"
        );
      }
    );
  }
);

describe(
  "SP no-op is byte-identity MODULO the accepted " +
    "variation-selector canonicalization",
  () => {
    it(
      "a second VS overwrites the first " +
        "(carried-over behaviour; arbitraries' " +
        "SP-conservation " +
        "exclusion 2), reached here from a STRANDED " +
        "selector",
      () => {
        // An SP edit can delete a glyph and leave its
        // VARIATION SELECTOR behind as a bare verbatim
        // anchor; seat that behind another
        // variation-carrying word and the SP text holds
        // two selectors in a row. parseSp folds the
        // second onto the word, which is the accepted
        // one-step canonicalization the arbitraries
        // exclude from the SP CONSERVATION law by
        // construction — this corpus can mint it, so
        // oracle 4's SP clause names the exclusion
        // instead of pretending it does not exist.
        const b: Block = {
          anchors: [
            {
              kind: "word",
              word: "toki",
              variation: 1,
            },
            { kind: "verbatim", text: "︀ " },
          ],
          gaps: [
            { sp: "", latin: "" },
            { sp: "", latin: " " },
            { sp: "", latin: "" },
          ],
          spans: [],
        };
        const before = renderSp(b).text;
        const after = renderSp(spNoOp(b)).text;
        // one selector short, everything else identical
        expect(before).not.toBe(after);
        expect(
          before.replace(/[︀-️]{2,}/gu, (m) =>
            m[m.length - 1]
          )
        ).toBe(after);
      }
    );
  }
);

// REGISTERED: the WHITESPACE-VERBATIM SPLIT-HALF
// MISALIGNMENT. A verbatim anchor whose text
// contains a space is re-tokenized by the Latin parse
// into two anchors; the rendered-text LCS then matches a
// NEIGHBOURING anchor against one of the halves, and the
// gap.sp bytes next to the seam die. A bare Latin no-op
// is enough. Duplication is irrelevant to the loss — it
// only decides whether oracle 3 notices — which is why
// the reproducer below has three DISTINCT texts.
//
// Registered as an accepted carve-out, so this pin
// asserts the exact CURRENT loss: any change in its
// shape must come past this test (verified
// pre-existing before the alignment-key fix).
describe(
  "accepted: a whitespace verbatim's split halves " +
    "mis-align and eat the neighbouring gap.sp",
  () => {
    it(
      "a bare Latin no-op turns 3 anchors into 4 and " +
        "DESTROYS the cartouche-end byte in gaps[1].sp",
      () => {
        const b: Block = {
          anchors: [
            {
              kind: "verbatim",
              text: "hi there",
              marked: true,
            },
            {
              kind: "verbatim",
              text: "hi",
              marked: true,
            },
            {
              kind: "verbatim",
              text: "yo dude",
              marked: true,
            },
          ],
          gaps: [
            { sp: " ", latin: "" },
            { sp: CARTOUCHE_END, latin: ", " },
            { sp: "\u3000", latin: ", " },
            { sp: "\u3000", latin: "" },
          ],
          spans: [],
        };
        expect(checkBlock(b)).toEqual([]);
        expect(renderLatin(b).text).toBe(
          "hi there, hi, yo dude"
        );
        const out = latinNoOp(b);
        // "hi there" re-tokenizes into "hi" + "there"
        expect(out.anchors).toEqual([
          { kind: "verbatim", text: "hi", marked: true },
          {
            kind: "verbatim",
            text: "there",
            marked: true,
          },
          { kind: "verbatim", text: "hi", marked: true },
          {
            kind: "verbatim",
            text: "yo dude",
            marked: true,
          },
        ]);
        // the exact loss: the CARTOUCHE_END byte is
        // gone, and an IDEO_SPACE has slid one gap left
        expect(
          out.gaps.map((g) => g.sp)
        ).toEqual([" ", "\u3000", " ", " ", "\u3000"]);
        expect(renderSp(b).text).toContain(
          CARTOUCHE_END
        );
        expect(renderSp(out).text).not.toContain(
          CARTOUCHE_END
        );
        // and it is a fixed point: the loss happens
        // once, on the first no-op
        expect(latinNoOp(out)).toEqual(out);
      }
    );
  }
);

// FIXED, by the LCS OCCURRENCE-AWARE SECONDARY
// KEYING in merge.ts. Found by the strengthened
// oracle 4a', which asserts identity for blocks the
// raw parse only appears to destabilize. The defect
// was NOT re-absorption: the rendered-text LCS
// (mergeBlockDetailed's alignKey) paired prev's
// FIRST "-" with next's only "-" and stranded the
// other in a region whose next side held no "-" at
// all, so absorbInto searched an empty haystack and
// the anchor died with its SP bytes. With the
// secondary keying, a key prev holds MORE OFTEN than
// next is disambiguated by FLANKING GAP CONTENT, so
// each occurrence pairs with the right one or with
// none — and this block is a full-identity NO-OP.
// The pin is a regression lock.
describe(
  "duplicate punctuation-only anchor texts " +
    "survive a Latin no-op (secondary keying)",
  () => {
    it(
      "a per-block Latin NO-OP is IDENTITY: every " +
        "anchor and every SP byte survives",
      () => {
        // Two marked verbatim "-" anchors, one of them
        // inside a cartouche that ATOMIZES (its
        // projected name is non-empty, so the
        // covered "-" is hidden behind the atom),
        // plus
        // a "314". The raw Latin parse returns every
        // punctuation-only anchor to gap.latin, so the
        // next side renders "-" ONCE where prev
        // holds it twice — the exact count asymmetry
        // the secondary key disambiguates.
        //
        // Fixture note: a version with EMPTY
        // gap.latin everywhere (zero flanking latin
        // — maximal reparse collapse) stopped
        // working when interior-punctuation runs
        // started binding whole: with no whitespace
        // at all the ENTIRE line — both "-"s, the
        // digit run, and the second "toki" — welds
        // into ONE bound token, losing the tail
        // "toki" as an independent word anchor. A
        // single real space at each seam (a shape
        // any real author actually types) provides
        // the hard boundaries, and "314" (not
        // "3.14") keeps the middle punct-only span
        // dissolving to gap.latin instead of MINTING
        // its own bound anchor (a digit run with an
        // interior dot binds on its own; a pure
        // digit run does not). The reparse-collapse
        // shape — and the secondary-key
        // disambiguation of the two surviving "-"
        // occurrences from flanking gap content — is
        // intact.
        const b: Block = {
          anchors: [
            { kind: "word", word: "ni" },
            { kind: "word", word: "toki" },
            {
              kind: "verbatim",
              text: "axxq",
              marked: true,
            },
            {
              kind: "verbatim",
              text: "-",
              marked: true,
            },
            {
              kind: "verbatim",
              text: "314",
              marked: true,
            },
            {
              kind: "verbatim",
              text: "-",
              marked: true,
            },
            { kind: "word", word: "toki" },
          ],
          gaps: [
            { sp: "", latin: "" },
            { sp: "", latin: " " },
            { sp: STACK, latin: " " },
            { sp: "　", latin: " " },
            { sp: "", latin: " " },
            { sp: "　", latin: " " },
            { sp: "", latin: " " },
            { sp: "", latin: "" },
          ],
          spans: [
            cart(1, 1),
            cart(3, 3),
            cart(5, 6),
          ],
        };
        // a well-formed block: this is not a shape the
        // model rejects, which is the point
        expect(checkBlock(b)).toEqual([]);
        const out = latinNoOp(b);
        // PRE-FIX: two anchors gone — "314" and one
        // "-" — and with them their SP text and an
        // IDEO_SPACE (out.anchors was length 5, and
        // out.gaps[3].latin held the orphaned "-314").
        // POST-FIX: the no-op is identity.
        expect(b.anchors).toHaveLength(7);
        expect(out).toEqual(b);
        const spText =
          "\u{F1941}\u{F1990}\u{F196C}\u{F1991}" +
          STACK +
          "axxq　\u{F1990}-\u{F1991}314　" +
          "\u{F1990}-\u{F196C}\u{F1991}";
        expect(renderSp(b).text).toBe(spText);
        expect(renderSp(out).text).toBe(spText);
        // and it is a true fixed point, not a one-step
        // coincidence
        expect(latinNoOp(out)).toEqual(out);
      }
    );
  }
);

// NOT a carve-out and NOT a defect — a normal-form
// CANONICALIZATION (see the NOT-CARVE-OUTS note in
// test/edit-corpus.ts). Found when the oracle-4a'
// fallthrough was removed, which is what had been
// swallowing it.
describe(
  "gap.latin interior to an ATOMIZING cartouche " +
    "re-homes outside the span, in one step",
  () => {
    it(
      "content is byte-preserved, anchors/spans/gap.sp " +
        "are untouched, and the second no-op is an " +
        "identity",
      () => {
        // The cartouche covers [verbatim, word]. Its
        // projected name is non-empty ("T"), so it
        // ATOMIZES — and renderLatin then emits that
        // name and nothing else for the whole span. The
        // "- " stored in gaps[2].latin, between the two
        // covered anchors, is therefore unreachable
        // through the Latin projection: no parse can
        // see it and no edit can address it.
        const b: Block = {
          anchors: [
            {
              kind: "verbatim",
              text: "-",
              marked: true,
            },
            { kind: "word", word: "toki" },
            {
              kind: "verbatim",
              text: "-",
              marked: true,
            },
            {
              kind: "verbatim",
              text: "-",
              marked: true,
            },
          ],
          gaps: [
            { sp: "  ", latin: "" },
            { sp: "", latin: "" },
            { sp: STACK, latin: "- " },
            { sp: "", latin: " " },
            { sp: "", latin: "" },
          ],
          spans: [
            cart(0, 0),
            cart(1, 2),
            cart(2, 2),
            cart(3, 3),
          ],
        };
        expect(checkBlock(b)).toEqual([]);
        // the interior "- " is invisible: the span
        // renders as its name alone
        expect(renderLatin(b).text).toBe("-T -");

        const once = latinNoOp(b);
        // ...and the normal form re-homes it OUTSIDE
        // the span, where it is visible again
        expect(once.gaps.map((g) => g.latin)).toEqual([
          "",
          "",
          "",
          " ",
          " -",
        ]);
        expect(renderLatin(once).text).toBe("-T - -");
        // BYTE-PRESERVED: the same latin characters, in
        // the same order, just outside the atom
        expect(
          b.gaps.map((g) => g.latin).join("")
        ).toBe("-  ");
        expect(
          once.gaps.map((g) => g.latin).join("")
        ).toBe("  -");
        // ...and NOTHING else moved: anchors, spans and
        // every gap.sp are byte-identical, so no span is
        // created or destroyed and the SP
        // pane does not change at all.
        expect(once.anchors).toEqual(b.anchors);
        expect(once.spans).toEqual(b.spans);
        expect(once.gaps.map((g) => g.sp)).toEqual(
          b.gaps.map((g) => g.sp)
        );
        expect(renderSp(once).text).toBe(
          renderSp(b).text
        );

        // ONE STEP: the second no-op is an identity, so
        // this is a canonicalization and not a ratchet.
        expect(latinNoOp(once)).toEqual(once);
      }
    );
  }
);
